sudo: false
language: node_js
node_js:
- '4.1'
services:
- docker
env:
  global:
  - secure: KQL/r2DFrDbrWf7TMeowxZDAd1FKb2HfP9gSGnCnREl3QEEXEPGdaBsBPzPZg4nGOmfDWi5oH3MVG73nFhZo3qO+1Vb3m4FyD2Qjr9IdvldIVIcp1YGz31zG5slB5mUZ5nP32cYVUo9ADTJmqcKOxRfthLd4Smwfc+e7NPsMM/+a9d/aZcKFKA9Rt7KAlmHdRHkP9iEBg1QqPbPhKoOvUO9EVgKkCw/LwsDtzAwCX7j5+kzKSwqeO2zaZFZQ6gQn9VdCI0FkbAOJ7V9ayzW3bLe89dAvPL2oGmAGxlgSYc3JgG/lNdI+diKbmTLVlDq72pGkS4kb++dbEv6ZJTJ3uYs2wUoSstksR/v7npt71zCWDy7qc769bA/xp+SfQvcR+U7XIuzDMPETBR4Q7UXNy33GmDISwNr2bNSYtGKnBEcDiL09CINLuv4q00teuQa8B1dnkLAv/hwTfORrh48pckH8qFKaWMO/iC700skTS1Cyi8Qri9Z5EP0eSxAVv/51Y54hIbcH/8knUXEsmPF8XIoSQ6y5UMRIGTCC50gVoEl7aRPBGnN2yBz2VVpLSdQw7Ifx4cYmP1d7Z7WSya/ubNT00jN2xcDng+hRi1VS4eRZjZykgowU1rsxnR+EcA2uhqN1I2sztcSFpVj8yN7nTfKfTCUBjUmqGLeIleCMv84= // IRON_TOKEN
  - secure: zvglZkgmaN8DQrALVcBYBlJ7bQB5qE1bDzk/CdQRrr8dVFhnER2TD4u1GFhL6vlS/2v53tRrO19zA4zEURTHcTQtghnez58gP8XNw/DfpIvjI03xFjHiL+wKjOjVRdnAD8k2AZV9cOQsf1oSVJRbfj8AvlVWt2hnXnFDt8Q3xII72AEKUNr790ezQ2kDzkbCNnwDdVAgt8zbHVWSQiJG3Nk6ZEZqxIhhQ4Z052NrRKpq3MgkOATuI6Tpf8isHJ4UtsVDW1yLG6Ypip9KJL7NA4VscthjMp8fvvBm6jG++2xTVE+FSpbR5/WuMokQuElxk41rZ8OD/rMTev/bms6crQWQytdxzTLpVDZsZbWD+dcOgwgqOdabihmMM/lUGCar2OA4XcWGsB/kysTYaLUA6fglfGe7AZbXRssuCPKHIgant/kk0k8eKDJvV8u+qgA1mi9sq5AOUqjLjT+Dd3v44S6CTbxedjNSUqggtW+4sDJO+qzBTlpfOcZiso4avHCsyMHa+xA883B6s4eWSxI6+aiL2F9LhHkxnQjCwQymU5EwGOXCSSbE9PZFoHHXmOSmGrp/aqCvj8cI8IKlEb269jgbdMcSOAANMLvjkS2g62fRC00NiHNAlGOvvxF+zGxAUTPOoHRRGV7d8cOvv5jOpAxHQ7qm1fAwirj94bGJZHs= // IRON_PROJECT_ID
install: echo nothing to install
script: docker-compose run --rm test
deploy:
  provider: script
  script: ".build_scripts/deploy.sh"
  on: master
